---
- name: get the date and time for the artifact
  set_fact:
    time: "{{ lookup('pipe', 'date +\"%Y-%b-%d-%H-%M-%S\"') }}-{{offline_installer_type}}"
  when: uploadInstaller is not defined

- name: create a directory to store artifacts
  file:
    path: "{{offline_repo_location}}/desktop_uploader_assets/{{time}}"
    state: directory
    recurse: yes
  when: uploadInstaller is not defined

- name: copy the installer script file and build script for building offline installer
  template:
    src: "{{item}}.j2"
    dest: "{{offline_repo_location}}/{{item}}"
    mode: '0755'
  with_items:
    - build.sh
    - envfile
  when: uploadInstaller is not defined

- name: copy the installer script file and build script for building offline installer
  template:
    src: "{{item}}.j2"
    dest: "{{offline_repo_location}}/{{item}}"
    mode: '0755'
  with_items:
    - setupOfflineInstaller.sh
  when: uploadInstaller is not defined

- name: run the installer script
  shell: "bash -x {{offline_repo_location}}/build.sh"
  when: uploadInstaller is not defined

- name: upload to azure
  include: uploadToAzure.yml
  when: uploadInstaller is defined
