{{- if .Values.prometheus.thanos }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thanos-compactor
  namespace: {{ $.Release.Namespace }}
  labels:
{{- if .Values.prometheus.prometheusSpec.thanosCompactorLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosCompactorLabels | indent 4 }}
{{- end }}
spec:
  serviceName: "thanos-compactor"
  replicas: 1
  selector:
    matchLabels:
{{- if .Values.prometheus.prometheusSpec.thanosCompactorLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosCompactorLabels | indent 6 }}
{{- end }}
  template:
    metadata:
      labels:
{{- if .Values.prometheus.prometheusSpec.thanosCompactorLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosCompactorLabels | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: thanos-compactor
        # Always use explicit image tags (release or master-<date>-sha) instead of ambigous `latest` or `master`.
        image: improbable/thanos:v0.2.1
        args:
        - "compact"
        - "--log.level=debug"
        - "--data-dir=/var/thanos/store"
        - "--objstore.config-file=/config/thanos-store.yml"
        - "--wait"
        ports:
        - name: http
          containerPort: 10902
        volumeMounts:
        - name: data
          mountPath: /var/thanos/store
        env:
        - name: config
          valueFrom:
            secretKeyRef:
              key: config
              name: thanos-objstore-config
      volumes:
      - name: data
        emptyDir: {}
      - name: config
        configMap:
          name: thanos-objstore-config
{{- end }}
