{{- if .Values.prometheus.prometheusSpec.thanos }}
apiVersion: v1
kind: Service
metadata:
  name: thanos-compactor
  labels:
    app: thanos-compactor
  namespace: {{ $.Release.Namespace }}
spec:
  selector:
    app: thanos-compactor
  ports:
  - port: 10902
    name: http
{{- end }}
