{{- if .Values.prometheus.thanos }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
{{- if .Values.prometheus.prometheusSpec.thanosLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosLabels | indent 4 }}
{{- end }}
  name: thanos-query
  namespace: {{ $.Release.Namespace }}
spec:
  ports:
  - name: grpc
    port: 10901
    targetPort: grpc
  - name: http
    port: 9090
    targetPort: http
  selector:
{{- if .Values.prometheus.prometheusSpec.thanosLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosLabels | indent 4 }}
{{- end }}
{{- end }}
