---
- name: copy the template file
  template:
    src: "{{item}}.j2"
    dest: "/tmp/{{item}}"
    mode: 0755
  with_items:
    - proxyvalidatorDeployment.yml
    - proxyvalidatorService.yml
  when: enable_proxyvalidator == true

- name: inject the proxyvalidator into apimanager pod
  shell: kubectl patch deployments.apps -n "{{namespace}}" apimanager --patch="$(cat /tmp/{{item}})"
  with_items:
    - proxyvalidatorDeployment.yml
    - proxyvalidatorService.yml
  when: enable_proxyvalidator == true

- name: delete the proxyvalidator
  shell: kubectl patch deployment -n "{{namespace}}" apimanager --type json -p='[{"op": "remove", "path": "/spec/template/spec/containers/0"}]'
  when: enable_proxyvalidator == false
