---
kong_admin_api_url: "http://{{kong_host}}:8001"

mobile_admin_groups:
  - mobileAdmin

mobile_app_groups:
  - mobileApp

mobile_device_groups:
  - contentUser
  - courseUser
  - appUpdate
  - configUser
  - publicUser
  - userUpdate
  - contentUpdate
  - domainUser
  - dataUpdate
  - dialcodeUser
  - echoUser
  - mobileApis

integration_partner_groups:
  - echoUser
  - orgAdmin
  - orgUpdate
  - orgUser
  - userAdmin
  - userUpdate
  - publicUser
  - dataAdmin
  - dataUpdate
  - domainAdmin
  - domainUpdate
  - domainUser
  - dialcodeAdmin
  - dialcodeUpdate
  - dialcodeUser
  - appAdmin
  - appUpdate
  - courseUser
  - contentUser
  - contentAdmin
  - contentUpdate
  - courseAdmin
  - courseUpdate
  - noteAdmin
  - noteUpdate
  - noteUser
  - configUser

implementaion_user_groups:
  - contentAdmin
  - contentUpdate
  - contentUser
  - userAdmin
  - userUpdate
  - publicUser
  - orgAdmin
  - orgUpdate
  - orgUser
  - courseAdmin
  - courseUpdate
  - courseUser
  - dialcodeAdmin
  - dialcodeUpdate
  - dialcodeUser
  - privateContentMgmt

# List all consumer groups in group_vars
kong_all_consumer_groups:
  - announcementAccess
  - appAcces
  - appAccess
  - appAdmin
  - appCreate
  - appUpdate
  - badgeAccess
  - badgeAdmin
  - badgeCreate
  - badgeUpdate
  - certificateAccess
  - certificateCreate
  - certificateUpdate
  - channelAccess
  - channelAdmin
  - channelCreate
  - channelUpdate
  - contentAccess
  - contentAdmin
  - contentCreate
  - contentUpdate
  - courseAccess
  - courseAdmin
  - courseCreate
  - courseUpdate
  - deviceCreate
  - dialcodeAccess
  - dialcodeAdmin
  - dialcodeCreate
  - dialcodeUpdate
  - experimentCreate
  - expirementAccess
  - formCreate
  - formUpdate
  - frameworkAccess
  - frameworkAdmin
  - frameworkCreate
  - frameworkUpdate
  - itemSetAdmin
  - locationAccess
  - locationAdmin
  - locationCreate
  - locationUpdate
  - noteAccess
  - noteAdmin
  - noteCreate
  - noteUpdate
  - objectAccess
  - objectAdmin
  - objectCreate
  - objectUpdate
  - orgAccess
  - orgAdmin
  - orgCreate
  - orgUpdate
  - pageAccess
  - pageCreate
  - pageUpdate
  - pluginAccess
  - ssoAdmin
  - ssoCreate
  - telemetryCreate
  - userAccess
  - userAdmin
  - userCreate
  - userUpdate

kong_admin_groups:
  - kongConsumer

private_groups:
  - locationAdmin

# List the consumers need to be present as state: present
# List the consumers need to be absent as state: absent
# This role will not update / delete consumers not listed here
kong_consumers:
  - username: api-admin
    groups: "{{ kong_all_consumer_groups }}"
    state: present
  - username: mobile_admin
    groups: "{{ mobile_admin_groups }}"
    print_credentials: true
    state: present
  - username: mobile_app
    groups: "{{ mobile_app_groups }}"
    state: present
  - username: mobile_device
    groups: "{{ mobile_device_groups }}"
    state: present
