---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: thanos-query
  namespace: {{ $.Release.Namespace }}
  labels:
    app: thanos-query
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thanos-query
  template:
    metadata:
      labels:
        app: thanos-query
{{- if .Values.prometheus.prometheusSpec.thanosLabels }}
{{ toYaml .Values.prometheus.prometheusSpec.thanosLabels | indent 8 }}
{{- end }}
    spec:
      containers:
      - name: thanos-query
        image: quay.io/thanos/thanos:v0.11.0
        args:
        - query
        - --log.level=debug
        - --query.replica-label=kubernetes
        - --store=dnssrv+_grpc._tcp.thanos-sidecar.monitoring.svc.cluster.local
        - --store=dnssrv+_grpc._tcp.thanos-store.monitoring.svc.cluster.local
        ports:
        - name: http
          containerPort: 10902
        - name: grpc
          containerPort: 10901

