{% if enable_thanos == "true" %}
prometheus:
  prometheusSpec:
    thanosLabels:
      app.kubernetes.io/component: query-layer
      app.kubernetes.io/instance: thanos-query
      app.kubernetes.io/name: thanos-query
{% endif %}
