{{ '{{' }}- if .Values.prometheus.prometheusSpec.thanosSecret {{ '}}' }}
apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: {{ '{{' }} default .Values.namespace .Release.Namespace  {{ '}}' }}
  labels:
    app: {{ '{{' }} template "prometheus-operator.name" . {{ '}}' }}-operator
{{ '{{' }} include "prometheus-operator.labels" . | indent 4 {{ '}}' }}
{{ '{{' }}- if .Values.prometheusOperator.service.labels {{ '}}' }}
{{ '{{' }} toYaml .Values.prometheusOperator.service.labels | indent 4 {{ '}}' }}
{{ '{{' }}- end {{ '}}' }}
data:
  thanos.yaml: {{ '{{' }} toYaml .Values.prometheus.prometheusSpec.thanosSecret | b64enc | quote {{ '}}' }}
{{ '{{' }}- end {{ '}}' }}
