
---
kong_admin_api_url: "http://{{kong_host}}:8001"

# Default statsd_metrics
statsd_metrics: ["request_count", "status_count", "latency", "upstream_latency", "request_size", "response_size"]
statsd_host: statsd-service
statsd_port: 9125

statsd_pulgin:
  name: statsd
  config.metrics: "{{ statsd_metrics }}"
  config.host: "{{ statsd_host }}"
  config.port: "{{ statsd_port }}"

# Default Rate limits
small_rate_limit_per_hour: 100
medium_rate_limit_per_hour: 5000
x_medium_rate_limit_per_hour: 5000
large_rate_limit_per_hour: 10000
x2_large_rate_limit_per_hour: 15000
x_large_rate_limit_per_hour: 30000

premium_consumer_small_rate_limit_per_hour: 1000
premium_consumer_medium_rate_limit_per_hour: 10000
premium_consumer_large_rate_limit_per_hour: 100000

# Default max request size in MB
small_request_size_limit: 1
medium_request_size_limit: 10
large_request_size_limit: 100

# Default service prefixes
private_content_prefix: /private/content
content_prefix: /content
course_service_prefix: /course
itemset_prefix: /itemset
user_service_prefix: /user
data_service_prefix: /data
notes_service_prefix: /notes
org_service_prefix: /org
echo_service_prefix: /echo
composite_service_prefix: /composite
api_manager_perfix: /api-manager
meta_service_prefix: /meta
dashboard_service_prefix: /dashboard
announcement_service_prefix: /announcement
dialcode_service_prefix: /dialcode
channel_service_prefix: /channel
framework_service_prefix: /framework
badge_service_prefix: /badging
plugin_service_prefix: /plugins
config_service_prefix: /config
textbook_service_prefix: /textbook
lock_service_prefix: /lock
otp_service_prefix: /otp
sso_service_prefix: /sso
cert_service_prefix: /cert
cert_registry_service_prefix: /certreg
desktop_app_prefix: /desktop
license_api_prefix: /license

# Service URLs
knowledge_mw_service_url: "http://knowledge-mw-service:5000"
learning_service_url: "http://learner-service:9000"
vm_learning_service_url: "http://{{learningservice_ip}}:8080/learning-service"
telemetry_service_url: "http://telemetry-service:9001"
player_service_url: "http://player:3000"
echo_service_url: "http://echo:9595"
am_util_url: "http://adminutil:4000"
config_service_url: "http://config-service:8080"
lms_service_url: "http://lms-service:9000"
cert_service_url: "http://cert-service:9000"
cert_registry_service_url: "http://cert-registry-service:9000"
content_service_url: "http://content-service:9000"

premium_consumer_rate_limits:
  - api: createContent
    config.hour: "{{ premium_consumer_small_rate_limit_per_hour }}"
    config.limit_by: credential
    config.policy: local
  - api: updateContent
    config.hour: "{{ premium_consumer_medium_rate_limit_per_hour }}"
    config.limit_by: credential
    config.policy: local
  - api: readContent
    config.hour: "{{ premium_consumer_large_rate_limit_per_hour }}"
    config.limit_by: credential
    config.policy: local

kong_apis:

# acceptContentFlag API DESCRIPTION: Accept the flagged content - via KMS
  - name: acceptContentFlag
    request_path: "{{ content_prefix }}/v1/flag/accept"
    upstream_url: "{{ knowledge_mw_service_url }}/v1/content/flag/accept"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['contentAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# acceptTermsAndCondition API DESCRIPTION: used to accent the terms and conditions
  - name: acceptTermsAndCondition
    request_path: "{{ user_service_prefix }}/v1/tnc/accept"
    upstream_url: "{{ learning_service_url }}/v1/user/tnc/accept"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['appAccess']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addBadgeToUser API DESCRIPTION: used to add badges to the issuer
  - name: addBadgeToUser
    request_path: "{{ user_service_prefix }}/v1/badges/add"
    upstream_url: "{{ learning_service_url }}/v1/user/badges/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['badgeCreate']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addMember API DESCRIPTION: used to add member to an organisation
  - name: addMember
    request_path: "{{ org_service_prefix }}/v1/member/add"
    upstream_url: "{{ learning_service_url }}/v1/org/member/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['orgAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addRegCertificate API DESCRIPTION: used to generate the certificate for the batch
  - name: addRegCertificate
    request_path: "{{ cert_registry_service_prefix }}/v1/certs/add"
    upstream_url: "{{ cert_registry_service_url }}/certs/v1/registry/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['certificateCreate']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addSystemSettings API DESCRIPTION: used to create system settings
  - name: addSystemSettings
    request_path: "{{ data_service_prefix }}/v1/system/settings/set"
    upstream_url: "{{ learning_service_url }}/v1/system/settings/set"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['appCreate']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addUserSkill API DESCRIPTION: used to add a skill
  - name: addUserSkill
    request_path: "{{ user_service_prefix }}/v1/skill/add"
    upstream_url: "{{ learning_service_url }}/v1/user/skill/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['userCreate ']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addUserSkillEndorsement API DESCRIPTION: endorse skills for the user
  - name: addUserSkillEndorsement
    request_path: "{{ user_service_prefix }}/v1/skill/endorse/add"
    upstream_url: "{{ learning_service_url }}/v1/user/skill/endorse/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['userCreate']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# addUserToBatch API DESCRIPTION: Add Users to invite-only batch for a course
  - name: addUserToBatch
    request_path: "{{ course_service_prefix }}/v1/batch/user/add"
    upstream_url: "{{ lms_service_url }}/v1/course/batch/users/add"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['courseCreate']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# assemblePage API DESCRIPTION: Fetches the data for entire page - fllter to page section
  - name: assemblePage
    request_path: "{{ data_service_prefix }}/v1/page/assemble"
    upstream_url: "{{ lms_service_url }}/v1/page/assemble"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['NOACL']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# assignRole API DESCRIPTION: used to assign roles to user
  - name: assignRole
    request_path: "{{ user_service_prefix }}/v1/role/assign"
    upstream_url: "{{ learning_service_url }}/v1/user/assign/role"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['userAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ large_request_size_limit }}"

# batchBulkEnrolment API DESCRIPTION: enroll all users provided in the csv
  - name: batchBulkEnrolment
    request_path: "{{ course_service_prefix }}/v1/batch/bulk/enrollment"
    upstream_url: "{{ lms_service_url }}/v1/batch/bulk/enrollment"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['courseSuperAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# batchBulkUnEnrolment API DESCRIPTION: to unenroll more than one user from a batch
  - name: batchBulkUnEnrolment
    request_path: "{{ course_service_prefix }}/v1/batch/bulk/unenrollment"
    upstream_url: "{{ lms_service_url }}/v1/batch/bulk/unenrollment"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['courseSuperAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"

# blockUser API DESCRIPTION: used to block the user
  - name: blockUser
    request_path: "{{ user_service_prefix }}/v1/block"
    upstream_url: "{{ learning_service_url }}/v1/user/block"
    strip_request_path: true
    plugins:
    - name: jwt
    - name: cors
    - "{{ statsd_pulgin }}"
    - name: acl
      config.whitelist: "['userAdmin']"
    - name: rate-limiting
      config.policy: local
      config.hour: "{{ x_medium_rate_limit_per_hour }}"
      config.limit_by: credential
    - name: request-size-limiting
      config.allowed_payload_size: "{{ small_request_size_limit }}"
